export const mockEvents = [
  {
    id: "1",
    type: "habit",
    attributes: {
      user_id: "1",
      name: "Swimming",
      description: "go to the pool at least 1 per week",
      frequency: "weekly",
      custom_frequency: {
        monday: false,
        tuesday: false,
        wednesday: true,
        thursday: false,
        friday: true,
        saturday: false,
        sunday: true,
      },
      start_datetime: "2024-05-01 15:30:00",
      end_datetime: "2024-05-31 15:30:00",
      status: "in_progress",
    },
  },
  {
    id: "2",
    type: "habit",
    attributes: {
      user_id: "1",
      name: "Coding",
      description: "Spend 1 hour per day to practice coding",
      frequency: "daily",
      custom_frequency: {
        monday: false,
        tuesday: false,
        wednesday: true,
        thursday: false,
        friday: true,
        saturday: false,
        sunday: true,
      },
      start_datetime: "2024-05-01 20:00:00",
      end_datetime: "2024-05-31 20:00:00",
      status: "completed",
    },
  },
  {
    id: "3",
    type: "habit",
    attributes: {
      user_id: "1",
      name: "Mediate",
      description: "Spend 10 minutes meditating right after waking up",
      frequency: "daily",
      custom_frequency: {
        monday: false,
        tuesday: false,
        wednesday: true,
        thursday: false,
        friday: true,
        saturday: false,
        sunday: true,
      },
      start_datetime: "2024-05-1 6:30:00",
      end_datetime: "2024-05-31 6:30:00",
      status: "in_progress",
    },
  },
];
